version: '3.8'

services:
  betanumerics:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PORT=8080
      - SECRET_KEY=dev-secret-key-change-in-production
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3 